### ISSUE TITLE
can't export

### ISSUE THREAD

**Issue by vladyxd** [Valery-AA/XNALara-io-Tools#4]
Python: Traceback (most recent call last):
  File "C:\Users\chesc\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\XNALaraMesh-BL4_X\export_obj.py", line 854, in _write
    scene.frame_set(frame, 0.0)
TypeError: Scene.frame_set(): required parameter "subframe" to be a keyword argument!
Python: Traceback (most recent call last):
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3519, in save_single
    fbx_objects_elements(root, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3301, in fbx_objects_elements
    fbx_data_light_elements(objects, lamp, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 595, in fbx_data_light_elements
    shadow_color = lamp.shadow_color
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'PointLight' object has no attribute 'shadow_color'

Also:

Python: Traceback (most recent call last):
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3519, in save_single
    fbx_objects_elements(root, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3301, in fbx_objects_elements
    fbx_data_light_elements(objects, lamp, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 595, in fbx_data_light_elements
    shadow_color = lamp.shadow_color
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'PointLight' object has no attribute 'shadow_color'

**Comment by Valery-AA** [comment]
Well, I am not sure how to put it in a helpful way, but this has nothing to do with this add-on and is rather

the only issue related to the XNA Lara add-on is `scene.frame_set(frame, 0.0)` which I will be fixing directly from the browser as it's nothing more than the blender version you're on requiring the value of `subframe` to be passed with a name instead of leaving said name implied

**Comment by vladyxd** [comment]
hi, yeah so I edited the python file with the changes you pointed, and yet I still get

Python: Traceback (most recent call last):
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3519, in save_single
    fbx_objects_elements(root, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 3301, in fbx_objects_elements
    fbx_data_light_elements(objects, lamp, scene_data)
  File "D:\Programs\Blender\4.3\scripts\addons_core\io_scene_fbx\export_fbx_bin.py", line 595, in fbx_data_light_elements
    shadow_color = lamp.shadow_color
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'PointLight' object has no attribute 'shadow_color'


so I'm quite uncertain what could be wrong.

What I did:
Downloaded https://www.deviantart.com/xzombiealix/art/Clementine-TWD-TFS-XPS-797326634
Imported it
Waited to load
Tried to export it as FBX.

But thanks for trying :)

**Comment by Valery-AA** [comment]
The change was made in the new release too btw no need for the manual editing.

Well, I'm really unable to further help, as the problem is within another add-on which is a built-in add-on, if the export was called from this addon it would be an error originating from XNALara-io-tools/some_file scene_fbx_io_something , can't look at the other comments on phone to get the proper name but that is basically it

I'd ask on blender forums, as a last ditch effort also try to reinstall blender to see if it's a matter of a broken default addon
